version: 2.1
orbs:
  python: circleci/python@1.5.0


jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.4
      - image: cimg/postgres:14.2
        environment:
          PG_USER: $DB_USER
          PG_PASSWD: $DB_PASSWD
          PG_DB: $DB_NAME
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.10.4/dist-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - python/install-packages:
          pkg-manager: pip
      - run:
         name: Install Dependencies
         command: |
           pip3 install --ser -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: Run tests
          command: python3 manage.py test


workflows:
  build_and_test: 
    jobs:
      - build-and-test
